language: cpp
compiler: gcc
sudo: require
dist: trusty

before_install:
  - sudo add-apt-repository ppa:beineri/opt-qt591-trusty -y
  - sudo apt-get update -qq

install: 
  - sudo apt-get -y install qt59base qt59declarative

before_script:
  - source /opt/qt*/bin/qt*-env.sh

script:
  - mkdir build
  - cd build
  - qmake ..
  - make
  - make check
